title: FXBuson Template Test
description: A simple docs page made from a template
theme: just-the-docs

url: https://fxbuson.github.io/fxbuson_pages_templates/

aux_links:
  Repository: https://github.com/fxbuson/fxbuson_pages_templates
